routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepositController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\ReferralController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');
Route::get('/about', [HomeController::class, 'about'])->name('home.about');
Route::get('/team', [HomeController::class, 'team'])->name('home.team');
Route::get('/offers', [HomeController::class, 'plans'])->name('home.plans');
Route::get('wapspeed', [HomeController::class, 'wapspeed'])->name('home.wapspeed');
Route::get('contact', [HomeController::class, 'contact'])->name('home.contact');
Route::get('why-us', [HomeController::class, 'whyUs'])->name('home.why-us');
Route::get('/register', [UserController::class, 'create'])->name('user.register');
Route::post('/user/store', [UserController::class, 'store'])->name('user.store');
Route::get('/register-success', [UserController::class, 'registerSuccess'])->name('user.register-success');
Route::get('/login', [AuthController::class, 'showLoginForm'])->name('user.login');
Route::post('/login', [AuthController::class, 'login'])->name('auth.login');
Route::post('/register', [UserController::class, 'store'])->name('user.register');
Route::get('/forgot-password', [UserController::class, 'forgotPassword'])->name('user.forgot-password');
Route::post('/send-password-reset-link', [UserController::class, 'sendPasswordResetLink'])->name('user.send-password-reset-link');
Route::get('/reset-password/{token}', [UserController::class, 'resetPassword'])->name('user.reset-password');
Route::post('/reset-password', [UserController::class, 'updatePassword'])->name('user.submit-password-reset');
Route::post('/deploy', [HomeController::class, 'deploy'])->name('deploy');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [UserController::class, 'dashboard'])->name('user.dashboard');

    Route::get('/users', [UserController::class, 'index'])->name('user.index');
    Route::get('/user/{id}/show', [UserController::class, 'show'])->name('user.show');
    Route::get('/user/{id}/edit', [UserController::class, 'edit'])->name('user.edit');
    Route::put('/user/{id}/update', [UserController::class, 'update'])->name('user.update');
    Route::delete('/user/{id}/delete', [UserController::class, 'destroy'])->name('user.destroy');
    Route::get('/user/{id}/fund-account', [UserController::class, 'fundAccount'])->name('user.fund-account');
    Route::get('/user/{id}/compose-email', [UserController::class, 'composeMail'])->name('user.compose-email');
    Route::post('/user/send-email', [UserController::class, 'sendMail'])->name('user.send-email');

    Route::post('/logout', [AuthController::class, 'logout'])->name('user.logout');


    Route::resource('paymentmethod', 'PaymentMethodController');

    Route::get('/deposit/{id}/pay', [DepositController::class, 'paymentPage'])->name('deposit.payment-page');
    Route::put('/deposit/{id}/confirmPayment', [DepositController::class, 'confirmPayment'])->name('deposit.confirm-payment');
    Route::put('/deposit/{id}/haspaid', [DepositController::class, 'hasPaid'])->name('deposit.has-paid');
    Route::put('/deposit/{id}/hasnotpaid', [DepositController::class, 'hasNotPaid'])->name('deposit.has-not-paid');
    Route::resource('deposit', 'DepositController');

    Route::resource('plans', 'PlanController');

    Route::post('/account/debit', [AccountController::class, 'debit'])->name('user.withdraw');
    Route::resource('account', 'AccountController')->except(['create']);
    Route::get('/account/{userid}/create', [AccountController::class, 'create'])->name('account.create');

    Route::resource('withdrawalmethod', 'WithdrawalMethodController');
    Route::resource('withdrawal', 'WithdrawalController');

    Route::get('/referrals', [ReferralController::class, 'index'])->name('user.referrals');
    Route::put('/referral/{id}/withdraw-bonus', [ReferralController::class, 'withdrawBonusToBalance'])->name('user.withdraw-referral-bonus');
});

app/PaymentMethod.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class PaymentMethod extends Model
{
    protected $fillable = ['name', 'symbol', 'address'];
}

app/Http/Controllers/PaymentMethodController.php
<?php

namespace App\Http\Controllers;

use App\PaymentMethod;
use Illuminate\Http\Request;

class PaymentMethodController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $methods = PaymentMethod::all();
        return view('dashboard.payment_method.index', compact('methods'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.payment_method.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = [
            'name' => $request->name,
            'symbol' => $request->symbol,
            'address' => $request->address
        ];
        $created = PaymentMethod::firstorcreate($data);

        if ($created) {
            return redirect(route('paymentmethod.index'))->with('message', 'New Payment Method Added');
        }
        return redirect(route('paymentmethod.index'))->withErrors(['error' => 'Payment Method was Not Added']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\PaymentMethod  $paymentMethod
     * @return \Illuminate\Http\Response
     */
    public function show(PaymentMethod $paymentMethod, $id)
    {
        $method = $paymentMethod->find($id);
        return view('dashboard.payment_method.show', compact('method'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\PaymentMethod  $paymentMethod
     * @return \Illuminate\Http\Response
     */
    public function edit(PaymentMethod $paymentMethod, $id)
    {
        $method = $paymentMethod->find($id);
        return view('dashboard.payment_method.edit', compact('method'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\PaymentMethod  $paymentMethod
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, PaymentMethod $paymentMethod, $id)
    {
        $data = [
            'name' => $request->name,
            'symbol' => $request->symbol,
            'address' => $request->address
        ];
        $updated = $paymentMethod->find($id)->update($data);

        if ($updated) {
            return redirect(route('paymentmethod.index'))->with('message', 'Payment Method Updated');
        }
        return redirect(route('paymentmethod.index'))->withErrors(['error' => 'Payment Method Not Updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\PaymentMethod  $paymentMethod
     * @return \Illuminate\Http\Response
     */
    public function destroy(PaymentMethod $paymentMethod, $id)
    {
        $deleted = $paymentMethod->find($id)->delete();

        if ($deleted) {
            return redirect(route('paymentmethod.index'))->with('message', 'Payment Method Deleted');
        }
        return redirect(route('paymentmethod.index'))->withErrors(['error' => 'Payment Method Not Deleted']);
    }
}

resources/views/dashboard/payment_method/create.blade.php
@extends('layouts.dashboard')
    @section('content')

        <div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-8">
					<div class="card" style="background: inherit;">

									<div class="card" style="background: inherit;">
										<div class="card-header" style="text-align: center;">
											<div class="card-title">Add Payment Method</div>
										</div>

										<form action="{{ route('paymentmethod.store') }}" method="post">
                                        @csrf
											<div class="card-body">
												<div class="form-group">
													<label for="squareInput">Name</label>
													<input type="text" name="name" class="form-control input-square" placeholder="Name">
												</div>
												<div class="form-group">
													<label for="squareInput">Symbol</label>
													<input type="text" class="form-control input-square" name="symbol" placeholder="Symbol">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Address</label>
													<input type="text" class="form-control input-square" name="address" placeholder="Address">
												</div>

												<div class="card-action" style="text-align: center;">
													<button class="btn btn-primary">Add</button>
												</div>

											</div>
										</form>

									</div>

					</div>

				</div>
			<div class="col-md-2"></div>
			</div>
    </form>
    @endsection

resources/views/dashboard/payment_method/edit.blade.php
@extends('layouts.dashboard')
    @section('content')

        <div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-8">
					<div class="card" style="background: inherit;">

									<div class="card" style="background: inherit;">
										<div class="card-header" style="text-align: center;">
											<div class="card-title">Edit Payment Method</div>
										</div>

										<form action="{{ route('paymentmethod.update', $method->id) }}" method="post">
                                        @method('PUT')
                                        @csrf
											<div class="card-body">
												<div class="form-group">
													<label for="squareInput">Name</label>
													<input type="text" name="name" class="form-control input-square" value="{{ $method->name }}" placeholder="Name">
												</div>
												<div class="form-group">
													<label for="squareInput">Symbol</label>
													<input type="text" class="form-control input-square" name="symbol" value="{{ $method->symbol }}" placeholder="Symbol">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Address</label>
													<input type="text" class="form-control input-square" name="address" value="{{ $method->address }}" placeholder="Address">
												</div>

												<div class="card-action" style="text-align: center;">
													<button class="btn btn-primary">Update</button>
												</div>

											</div>
										</form>

									</div>

					</div>

				</div>
			<div class="col-md-2"></div>
			</div>
    </form>
    @endsection

resources/views/dashboard/payment_method/index.blade.php
@extends('layouts.dashboard')

    @section('content')

@php
$sn = 1;
@endphp
    <div class="col-md-12">
								<div class="card card-tasks">
									<div class="card-header ">
										<h4 class="card-title">Payment Methods</h4>
										<a href="{{ route('paymentmethod.create') }}" class="btn btn-primary"><span class="la la-plus"></span>Add</a>
									</div>
									<div class="card-body ">
										<div class="table-responsive">
											<table class="table">
												<thead>
													<tr>
														<th>#</th>
														<th>Name</th>
														<th>Method</th>
                                                        <th>Action</th>
													</tr>
												</thead>

												<tbody>
													@forelse ($methods as $method)
                                                        <tr>
                                                            <td>{{ $sn++ }}</td>
                                                            <td>{{ $method->name }}</td>
                                                            <td>{{ $method->symbol }}</td>
                                                            <td>{{ $method->address }}</td>
                                                            <td>
                                                                <a href="{{ route('paymentmethod.edit', $method->id) }}" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                                                                <button class="btn btn-danger btn-sm" onclick="event.preventDefault(); $('#destroy-method-{{ $method->id }}').submit();"><i class="fa fa-trash"></i></button>
                                                                <form action="{{ route('paymentmethod.destroy', $method->id) }}" id="destroy-method-{{ $method->id }}" method="post">
                                                                    @method('DELETE')
                                                                    @csrf
                                                                </form>
                                                            </td>
                                                        </tr>
                                                    @empty
                                                        <tr>
                                                            <td colspan="100%">no payment methods found</td>
                                                        </tr>
                                                    @endforelse
												</tbody>

											</table>
										</div>
									</div>
									<div class="card-footer ">

									</div>
								</div>
							</div>
    @endsection

resources/views/dashboard/payment_method/show.blade.php
@include('dashboard.payment_method.menu')

<table>
    <th>Method</th>
    <th>Address</th>

        <tr>
            <td>{{ $method->method }}</td>
            <td>{{ $method->address }}</td>
        </tr>

</table>