routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepositController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\ReferralController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');
Route::get('/about', [HomeController::class, 'about'])->name('home.about');
Route::get('/team', [HomeController::class, 'team'])->name('home.team');
Route::get('/offers', [HomeController::class, 'plans'])->name('home.plans');
Route::get('wapspeed', [HomeController::class, 'wapspeed'])->name('home.wapspeed');
Route::get('contact', [HomeController::class, 'contact'])->name('home.contact');
Route::get('why-us', [HomeController::class, 'whyUs'])->name('home.why-us');
Route::get('/register', [UserController::class, 'create'])->name('user.register');
Route::post('/user/store', [UserController::class, 'store'])->name('user.store');
Route::get('/register-success', [UserController::class, 'registerSuccess'])->name('user.register-success');
Route::get('/login', [AuthController::class, 'showLoginForm'])->name('user.login');
Route::post('/login', [AuthController::class, 'login'])->name('auth.login');
Route::post('/register', [UserController::class, 'store'])->name('user.register');
Route::get('/forgot-password', [UserController::class, 'forgotPassword'])->name('user.forgot-password');
Route::post('/send-password-reset-link', [UserController::class, 'sendPasswordResetLink'])->name('user.send-password-reset-link');
Route::get('/reset-password/{token}', [UserController::class, 'resetPassword'])->name('user.reset-password');
Route::post('/reset-password', [UserController::class, 'updatePassword'])->name('user.submit-password-reset');
Route::post('/deploy', [HomeController::class, 'deploy'])->name('deploy');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [UserController::class, 'dashboard'])->name('user.dashboard');

    Route::get('/users', [UserController::class, 'index'])->name('user.index');
    Route::get('/user/{id}/show', [UserController::class, 'show'])->name('user.show');
    Route::get('/user/{id}/edit', [UserController::class, 'edit'])->name('user.edit');
    Route::put('/user/{id}/update', [UserController::class, 'update'])->name('user.update');
    Route::delete('/user/{id}/delete', [UserController::class, 'destroy'])->name('user.destroy');
    Route::get('/user/{id}/fund-account', [UserController::class, 'fundAccount'])->name('user.fund-account');
    Route::get('/user/{id}/compose-email', [UserController::class, 'composeMail'])->name('user.compose-email');
    Route::post('/user/send-email', [UserController::class, 'sendMail'])->name('user.send-email');

    Route::post('/logout', [AuthController::class, 'logout'])->name('user.logout');


    Route::resource('paymentmethod', 'PaymentMethodController');

    Route::get('/deposit/{id}/pay', [DepositController::class, 'paymentPage'])->name('deposit.payment-page');
    Route::put('/deposit/{id}/confirmPayment', [DepositController::class, 'confirmPayment'])->name('deposit.confirm-payment');
    Route::put('/deposit/{id}/haspaid', [DepositController::class, 'hasPaid'])->name('deposit.has-paid');
    Route::put('/deposit/{id}/hasnotpaid', [DepositController::class, 'hasNotPaid'])->name('deposit.has-not-paid');
    Route::resource('deposit', 'DepositController');

    Route::resource('plans', 'PlanController');

    Route::post('/account/debit', [AccountController::class, 'debit'])->name('user.withdraw');
    Route::resource('account', 'AccountController')->except(['create']);
    Route::get('/account/{userid}/create', [AccountController::class, 'create'])->name('account.create');

    Route::resource('withdrawalmethod', 'WithdrawalMethodController');
    Route::resource('withdrawal', 'WithdrawalController');

    Route::get('/referrals', [ReferralController::class, 'index'])->name('user.referrals');
    Route::put('/referral/{id}/withdraw-bonus', [ReferralController::class, 'withdrawBonusToBalance'])->name('user.withdraw-referral-bonus');
});

app/Plan.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    protected $fillable = ['name', 'description','percentage','duration','min','max'];

    public static function validateForm()
    {
        $values = request()->validate(
            [
                'name' => 'required',
                'description' => 'required',
                'percentage' => 'required',
                'duration' => 'required',
                'min' => 'required',
                'max' => 'required'
            ]
        );
        return $values;
    }
}

app/Http/Controllers/PlanController.php
<?php

namespace App\Http\Controllers;

use App\Plan;
use Illuminate\Http\Request;

class PlanController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Plan $plan)
    {
        $plans = $plan->all();
        return view('dashboard.plans.index', compact('plans'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.plans.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $values = Plan::validateForm();
        $stored = Plan::create($values);

        if ($stored) {
            return redirect(route('plans.index'))->with('message', 'Plan added');
        }
        return redirect()->back()->withErrors(['error' => 'Plan no added']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function show(Plan $plan)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $plan = Plan::find($id);
        return view('dashboard.plans.edit', compact('plan'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function update($id)
    {
        $values = Plan::validateForm();
        $updated = Plan::find($id)->update($values);

        if ($updated) {
            return redirect(route('plans.index'))->with('message', 'plan updated');
        }
        return redirect()->back()->withErrors(['error' => 'plan not updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Plan  $plan
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = Plan::find($id)->delete();

        if ($deleted) {
            return redirect(route('plans.index'))->with('message', 'Plan Deleted');
        }
        return redirect(route('plans.index'))->withErrors(['error' => 'Plan Not Deleted']);
    }
}

resources/views/dashboard/plans/create.blade.php
@extends('layouts.dashboard')
    @section('content')

        <div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-8">
					<div class="card">
									<div class="card" style="background: inherit;">
										<div class="card-header" style="text-align: center;">
											<div class="card-title">Add Plan</div>
										</div>

										<form action="{{ route('plans.store') }}" method="post">
                                        @csrf
											<div class="card-body">
												<div class="form-group">
													<label for="squareInput">Plan</label>
													<input type="text" name="name" class="form-control input-square" placeholder="Name of plan">
												</div>
												<div class="form-group">
													<label for="squareInput">Description</label>
													<input type="text" class="form-control input-square" name="description" placeholder="Description">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Percentage</label>
													<input type="text" class="form-control input-square" name="percentage" placeholder="Percentage">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Duration</label>
													<input type="number" class="form-control input-square" name="duration" placeholder="Duration in days">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Minimum</label>
													<input type="number" class="form-control input-square" name="min" placeholder="Minimum">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Maximum</label>
													<input type="number" class="form-control input-square" name="max" placeholder="Maximum">
												</div>

												<div class="card-action" style="text-align: center;">
													<button class="btn btn-primary">Add</button>
												</div>

											</div>
										</form>

									</div>

					</div>

				</div>
			<div class="col-md-2"></div>
			</div>
    </form>
    @endsection

resources/views/dashboard/plans/edit.blade.php
@extends('layouts.dashboard')
    @section('content')

        <div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-8">
					<div class="card">
									<div class="card" style="background: inherit;">
										<div class="card-header" style="text-align: center;">
											<div class="card-title">Edit Plan</div>
										</div>

										<form action="{{ route('plans.update', $plan->id) }}" method="post">
                                        @method('PUT')
                                        @csrf
											<div class="card-body">
												<div class="form-group">
													<label for="squareInput">Plan</label>
													<input type="text" name="name" class="form-control input-square" placeholder="Name of plan" value="{{ $plan->name }}">
												</div>
												<div class="form-group">
													<label for="squareInput">Description</label>
													<input type="text" class="form-control input-square" name="description" placeholder="Description" value="{{ $plan->description }}">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Percentage</label>
													<input type="text" class="form-control input-square" name="percentage" placeholder="Percentage" value="{{ $plan->percentage }}">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Duration</label>
													<input type="number" class="form-control input-square" name="duration" placeholder="Duration in days" value="{{ $plan->duration }}">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Minimum</label>
													<input type="number" class="form-control input-square" name="min" placeholder="Minimum" value="{{ $plan->min }}">
												</div>
                                                <div class="form-group">
													<label for="squareInput">Maximum</label>
													<input type="number" class="form-control input-square" name="max" placeholder="Maximum" value="{{ $plan->max }}">
												</div>

												<div class="card-action" style="text-align: center;">
													<button class="btn btn-primary">Update</button>
												</div>

											</div>
										</form>

									</div>

					</div>

				</div>
			<div class="col-md-2"></div>
			</div>
    </form>
    @endsection

resources/views/dashboard/plans/index.blade.php
@extends('layouts.dashboard')
@section('content')

@php
$sn = 1;
@endphp
    <div class="col-md-12">
								<div class="card card-tasks">
									<div class="card-header ">
										<h4 class="card-title">All plans</h4>
										<a href="{{ route('plans.create') }}" class="btn btn-primary btn-sm"><span class="la la-plus"></span>Add</a>
									</div>
									<div class="card-body ">
										<div class="table-responsive">
											<table class="table">
												<thead>
													<tr>
														<th>#</th>
														<th>Name</th>
														<th>Description</th>
                                                        <th>Percentage</th>
                                                        <th>Duration</th>
                                                        <th>Minimum</th>
                                                        <th>Maximum</th>
                                                        <th>Action</th>
													</tr>
												</thead>

												<tbody>
													@forelse ($plans as $plan)
                                                        <tr>
                                                            <td>{{ $sn++ }}</td>
                                                            <td>{{ $plan->name }}</td>
                                                            <td>{{ $plan->description }}</td>
                                                            <td>{{ $plan->percentage }}%</td>
                                                            <td>{{ $plan->duration }} days</td>
                                                            <td>${{ $plan->min }}</td>
                                                            <td>${{ $plan->max }}</td>
                                                            <td>
                                                                <a href="{{ route('plans.edit', $plan->id) }}" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                                                                <button class="btn btn-danger btn-sm" onclick="event.preventDefault(); $('#destroy-plan-{{ $plan->id }}').submit();"><i class="fa fa-trash"></i></button>
                                                                <form action="{{ route('plans.destroy', $plan->id) }}" method="post" id="destroy-plan-{{ $plan->id }}">
                                                                    @method('DELETE')
                                                                    @csrf
                                                                </form>
                                                            </td>
                                                        </tr>
                                                    @empty
                                                        <tr>
                                                            <td colspan="100%">No plans found</td>
                                                        </tr>
                                                    @endforelse
												</tbody>

											</table>
										</div>
									</div>
									<div class="card-footer ">
										<div class="stats">

										</div>
									</div>
								</div>
							</div>
    @endsection