routes/web.php
<?php

use App\Http\Controllers\AccountController;
use App\Http\Controllers\AuthController;
use App\Http\Controllers\DepositController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentMethodController;
use App\Http\Controllers\ReferralController;
use App\Http\Controllers\UserController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'])->name('home.index');
Route::get('/about', [HomeController::class, 'about'])->name('home.about');
Route::get('/team', [HomeController::class, 'team'])->name('home.team');
Route::get('/offers', [HomeController::class, 'plans'])->name('home.plans');
Route::get('wapspeed', [HomeController::class, 'wapspeed'])->name('home.wapspeed');
Route::get('contact', [HomeController::class, 'contact'])->name('home.contact');
Route::get('why-us', [HomeController::class, 'whyUs'])->name('home.why-us');
Route::get('/register', [UserController::class, 'create'])->name('user.register');
Route::post('/user/store', [UserController::class, 'store'])->name('user.store');
Route::get('/register-success', [UserController::class, 'registerSuccess'])->name('user.register-success');
Route::get('/login', [AuthController::class, 'showLoginForm'])->name('user.login');
Route::post('/login', [AuthController::class, 'login'])->name('auth.login');
Route::post('/register', [UserController::class, 'store'])->name('user.register');
Route::get('/forgot-password', [UserController::class, 'forgotPassword'])->name('user.forgot-password');
Route::post('/send-password-reset-link', [UserController::class, 'sendPasswordResetLink'])->name('user.send-password-reset-link');
Route::get('/reset-password/{token}', [UserController::class, 'resetPassword'])->name('user.reset-password');
Route::post('/reset-password', [UserController::class, 'updatePassword'])->name('user.submit-password-reset');
Route::post('/deploy', [HomeController::class, 'deploy'])->name('deploy');

Route::middleware(['auth'])->group(function () {
    Route::get('/dashboard', [UserController::class, 'dashboard'])->name('user.dashboard');

    Route::get('/users', [UserController::class, 'index'])->name('user.index');
    Route::get('/user/{id}/show', [UserController::class, 'show'])->name('user.show');
    Route::get('/user/{id}/edit', [UserController::class, 'edit'])->name('user.edit');
    Route::put('/user/{id}/update', [UserController::class, 'update'])->name('user.update');
    Route::delete('/user/{id}/delete', [UserController::class, 'destroy'])->name('user.destroy');
    Route::get('/user/{id}/fund-account', [UserController::class, 'fundAccount'])->name('user.fund-account');
    Route::get('/user/{id}/compose-email', [UserController::class, 'composeMail'])->name('user.compose-email');
    Route::post('/user/send-email', [UserController::class, 'sendMail'])->name('user.send-email');

    Route::post('/logout', [AuthController::class, 'logout'])->name('user.logout');


    Route::resource('paymentmethod', 'PaymentMethodController');

    Route::get('/deposit/{id}/pay', [DepositController::class, 'paymentPage'])->name('deposit.payment-page');
    Route::put('/deposit/{id}/confirmPayment', [DepositController::class, 'confirmPayment'])->name('deposit.confirm-payment');
    Route::put('/deposit/{id}/haspaid', [DepositController::class, 'hasPaid'])->name('deposit.has-paid');
    Route::put('/deposit/{id}/hasnotpaid', [DepositController::class, 'hasNotPaid'])->name('deposit.has-not-paid');
    Route::resource('deposit', 'DepositController');

    Route::resource('plans', 'PlanController');

    Route::post('/account/debit', [AccountController::class, 'debit'])->name('user.withdraw');
    Route::resource('account', 'AccountController')->except(['create']);
    Route::get('/account/{userid}/create', [AccountController::class, 'create'])->name('account.create');

    Route::resource('withdrawalmethod', 'WithdrawalMethodController');
    Route::resource('withdrawal', 'WithdrawalController');

    Route::get('/referrals', [ReferralController::class, 'index'])->name('user.referrals');
    Route::put('/referral/{id}/withdraw-bonus', [ReferralController::class, 'withdrawBonusToBalance'])->name('user.withdraw-referral-bonus');
});

app/WithdrawalMethod.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class WithdrawalMethod extends Model
{
    protected $fillable = ['name'];
}

app/Http/Controllers/WithdrawalMethodController.php
<?php

namespace App\Http\Controllers;

use App\WithdrawalMethod;
use Illuminate\Http\Request;

class WithdrawalMethodController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $methods = WithdrawalMethod::orderBy('id', 'desc')->get();
        return view('dashboard.withdrawal_methods.index', compact('methods'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.withdrawal_methods.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $stored = WithdrawalMethod::create($request->all());

        if ($stored) {
            return redirect(route('withdrawalmethod.index'))->with('message', 'New Withdrawal Method Added');
        }
        return redirect()->back()->withErrors(['error' => 'Withdrawal method was not added']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\WithdrawalMethod  $withdrawalMethod
     * @return \Illuminate\Http\Response
     */
    public function show(WithdrawalMethod $withdrawalMethod)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\WithdrawalMethod  $withdrawalMethod
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $method = WithdrawalMethod::find($id);
        return view('dashboard.withdrawal_methods.edit', compact('method'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\WithdrawalMethod  $withdrawalMethod
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $updated = WithdrawalMethod::find($id)->update($request->all());

        if ($updated) {
            return redirect(route('withdrawalmethod.index'))->with('message', 'Withdrawal method updated');
        }
        return redirect()->back()->withErrors(['error' => 'withdrawal method not updated']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\WithdrawalMethod  $withdrawalMethod
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleted = WithdrawalMethod::find($id)->delete();

        if ($deleted) {
            return redirect(route('withdrawalmethod.index'))->with('message', 'Withdrawal Method deleted');
        }
        return redirect()->back()->withErrors(['error' => 'withdrawal method not deleted']);
    }
}

resources/views/dashboard/withdrawal_methods/create.blade.php
@extends('layouts.dashboard')
    @section('content')

        <div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-8">
					<div class="card" style="background: inherit;">

									<div class="card" style="background: inherit;">
										<div class="card-header" style="text-align: center;">
											<div class="card-title">Add Withdrawal Method</div>
										</div>

										<form action="{{ route('withdrawalmethod.store') }}" method="post">
                                        @csrf
											<div class="card-body">
												<div class="form-group">
													<label for="squareInput">Name</label>
													<input type="text" name="name" class="form-control input-square" placeholder="Name">
												</div>
												
												<div class="card-action" style="text-align: center;">
													<button class="btn btn-primary">Add</button>
												</div>

											</div>
										</form>

									</div>

					</div>

				</div>
			<div class="col-md-2"></div>
			</div>
    </form>
    @endsection

resources/views/dashboard/withdrawal_methods/edit.blade.php
@extends('layouts.dashboard')
    @section('content')

        <div class="row">
				<div class="col-md-2"></div>
				<div class="col-md-8">
					<div class="card" style="background: inherit;">

									<div class="card" style="background: inherit;">
										<div class="card-header" style="text-align: center;">
											<div class="card-title">Edit Withdrawal Method</div>
										</div>

										<form action="{{ route('withdrawalmethod.update', $method->id) }}" method="post">
                                            @method('PUT')
                                        @csrf
											<div class="card-body">
												<div class="form-group">
													<label for="squareInput">Name</label>
													<input type="text" name="name" class="form-control input-square" placeholder="Name" value="{{ $method->name }}">
												</div>

												<div class="card-action" style="text-align: center;">
													<button class="btn btn-primary">Update</button>
												</div>

											</div>
										</form>

									</div>

					</div>

				</div>
			<div class="col-md-2"></div>
			</div>
    </form>
    @endsection

resources/views/dashboard/withdrawal_methods/index.blade.php
@extends('layouts.dashboard')

    @section('content')

@php
$sn = 1;
@endphp
    <div class="col-md-12">
        <div class="card card-tasks">
            <div class="card-header ">
                <h4 class="card-title">Withdrawal Methods</h4>
                <a href="{{ route('withdrawalmethod.create') }}" class="btn btn-primary"><span class="la la-plus"></span>Add</a>
            </div>
            <div class="card-body ">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>#</th>
                                <th>Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>

                        <tbody>
                            @forelse ($methods as $method)
                                <tr>
                                    <td>{{ $sn++ }}</td>
                                    <td>{{ $method->name }}</td>
                                    <td>
                                        <a href="{{ route('withdrawalmethod.edit', $method->id) }}" class="btn btn-warning btn-sm"><i class="fa fa-edit"></i></a>
                                        <button class="btn btn-danger btn-sm" onclick="event.preventDefault(); $('#destroy-method-{{ $method->id }}').submit();"><i class="fa fa-trash"></i></button>
                                        <form action="{{ route('withdrawalmethod.destroy', $method->id) }}" id="destroy-method-{{ $method->id }}" method="post">
                                            @method('DELETE')
                                            @csrf
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="100%">no withdrawal methods found</td>
                                </tr>
                            @endforelse
                        </tbody>

                    </table>
                </div>
            </div>
            <div class="card-footer ">

            </div>
        </div>
    </div>
    @endsection